<?php
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$this->headTitle( $title = $this->translate( 'customize.list.css.title', 'customize' ) );
$view   = $this;
$rowSet = $this->rowSet();

if ( ! $this->format ): ?>
<h1><?= $title ?></h1>
<?php endif ?>
<?= $this->rowSet( $this->paginator, $rowSet::FLAG_LAYOUT_ALL )
         ->setColumnTranslatePrefix( 'customize.list.css.column' )
         ->setColumnTranslatePostfix( 'title' )
         ->setColumnTranslateTextDomain( 'customize' )
         ->setPage( $this->page )
         ->setColumns( array(
              'type'    => $rowSet->column( $rowSet::TRANSLATE, 'paragraph.type', '', 'paragraph' ),
              'name'    => function ( $row ) use ( $view ) {
                return $row->type == 'metaContent'
                     ? '<i>' . $view->translate( 'paragraph.metaContent.' . $row->name, 'paragraph' ) . '</i>'
                     : $row->name;
              },
              'updated' => $rowSet::DATETIME,
              'actions' => function ( $row ) use ( $view ) {
                $view->placeholder( 'listActions' )->set( '' );
                $view->placeholder( 'listActions' )->captureStart();
?>
    <a class="action-button edit"
       title="<?= $view->translate( 'default.edit' ); ?>"
       href="/app/<?= $view->locale() ?>/admin/customize-css/edit/<?= $row->id ?>">
    </a>
<?php
                $view->placeholder( 'listActions' )->captureEnd();
                return (string) $view->placeholder( 'listActions' );
              },
          ) )
         ->render( $this->format );
