<?php
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$this->headTitle( $title = $this->translate( 'customize.list.css.title', 'customize' ) );
$view   = $this;
$rowSet = $this->rowSet();

if ( ! $this->format ): ?>
<h1><?= $title ?></h1>
<?php endif ?>
<?= $this->rowSet( $this->paginator, $rowSet::FLAG_LAYOUT_ALL )
         ->setColumnTranslatePrefix( 'customize.list.css.column' )
         ->setColumnTranslatePostfix( 'title' )
         ->setColumnTranslateTextDomain( 'customize' )
         ->setPage( $this->page )
         ->setNotSetLabels( array(
              'type'    => 'customize.list.css.column.type.global',
         ) )
         ->setColumns( array(
              'type'    => $rowSet->column( $rowSet::TRANSLATE, 'paragraph.type', '', 'paragraph' ),
              'name'    => function ( $row ) use ( $view ) {
                if ( empty( $row->id ) )
                {
                    return '<i>' . $view->translate(
                        'customize.list.css.column.type.global',
                        'customize'
                    ) . '</i>';
                }

                return $row->type == 'metaContent'
                     ? '<i>' . $view->translate( 'paragraph.metaContent.' . $row->name, 'paragraph' ) . '</i>'
                     : $row->name;
              },
              'updated' => $rowSet::DATETIME,
              'actions' => function ( $row ) use ( $view ) {
                $id = empty( $row->id ) ? 'global' : (int) $row->id;
                $view->placeholder( 'listActions' )->set( '' );
                $view->placeholder( 'listActions' )->captureStart();
?>
    <a class="action-button edit"
       title="<?= $view->translate( 'default.edit' ); ?>"
       href="/app/<?= $view->locale() ?>/admin/customize-css/edit/<?= $id ?>">
    </a>
<?php if ( ! empty( $row->id ) && $row->type != 'metaContent' ): ?>

    <a class="action-button export"
       title="<?= $view->translate( 'default.export' ); ?>"
       href="/app/<?= $view->locale() ?>/admin/customize/export/<?= $id ?>">
    </a>
<?php endif;
                $view->placeholder( 'listActions' )->captureEnd();
                return (string) $view->placeholder( 'listActions' );
              },
          ) )
         ->render( $this->format );

if ( ! $this->format &&
       $this->isAllowed( 'customize', 'create' ) &&
       $this->isAllowed( 'paragraph', 'create' ) ): ?>
<div class="more-links">
    <a class="button-appearance"
       href="/app/<?= $view->locale() ?>/admin/customize/import">
        <?= $view->translate( 'customize.form.import.title' ); ?>
    </a>
</div>
<?php endif;
