<?php $root = $this->viewModel()->getRoot();
if ( empty( $root->content ) ): ?>
    <div class="paragraph-like visual-content-placeholder">
        <h1><?= $this->translate( 'paragraph.type.contentPlaceholder', 'paragraph' ) ?></h1>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Nam eu condimentum est. In mattis odio non elit fermentum porttitor.
            Nam et felis quis dui vestibulum faucibus. Curabitur molestie rutrum porta.
            Mauris cursus, nisl quis tincidunt auctor, mi neque facilisis nisl,
            quis adipiscing elit magna eget libero. Nam imperdiet pretium dolor,
            in mattis lectus sodales luctus. Vestibulum ante ipsum primis in faucibus
            orci luctus et ultrices posuere cubilia Curae.
        </p>
    </div>
<?php else: ?>
    <?= $root->content ?>
<?php endif ?>
