<ul class="language-variants">
<?php foreach ( $this->paragraph->getLinks() as $locale => $link ):
        $title = $this->translate( 'locale.sub.' . $locale, 'locale', $locale ); ?>

    <li data-js-locale="<?= $locale ?>"
        class="language-variant language-<?= \Locale::getPrimaryLanguage( $locale )
        ?> locale-<?= $locale ?><?php if ( $link['selected'] ):
        ?> selected<?php endif ?><?php if ( $link['active'] ):
        ?> active<?php endif ?>" title="<?= $this->escapeHtmlAttr( $title ) ?>">
        <a hreflang="<?= str_replace( '_', '-', $locale ) ?>"
           href="<?= $link['uri']?>"><?= $this->escapeHtml( $title ) ?></a>
    </li>
<?php endforeach ?>

</ul>
