<?php

$this->headTitle()
     ->splice( 1, 0, array( $this->paragraph->title ) );

if ( ! empty( $this->paragraph->metaRobots ) )
{
    $this->headMeta()
         ->setName( 'robots', $this->paragraph->metaRobots );
}

if ( ! empty( $this->paragraph->metaKeywords ) )
{
    $this->headMeta()
         ->setName( 'keywords', $this->paragraph->metaKeywords );
}

if ( ! empty( $this->paragraph->metaDescription ) )
{
    $this->headMeta()
         ->setName( 'description', $this->paragraph->metaDescription );
}
