<?php $this->headLink()
           ->appendStylesheet( '/styles/wizard.css', 'all' );

?><div class="wizard">
    <div class="wizard-step">
        <ul class="step-stack ui-helper-clearfix">
            <li><a href="#"><?= $this->translate( 'default.finish' ) ?></a></li>
        </ul>
        <div class="step-action step-action-finish">
            <?= $this->content ?>

        </div>
    </div>
</div>
