<?php

use Zend\Authentication\AuthenticationService;

/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$this->headTitle( $title = $this->translate(
    'admin.navTop.packages',
    'admin'
) );

$paginator = $this->paginator;
$auth      = new AuthenticationService();

$paginator->setPageRange( 7 )
          ->setItemCountPerPage( 6 )
          ->setCurrentPageNumber( $this->page );

$this->headLink()
     ->appendStylesheet( '/styles/packages.css' );

$filter = (array) $this->filter;

if ( empty( $filter['contains'] ) )
{
    $filter['contains'] = '';
}

if ( ! isset( $filter['installed'] ) || '' === $filter['installed'] )
{
    $filter['installed'] = null;
}

$locale = (string) $this->locale();

?>
<h1><?= $title ?></h1>
<div class="page">
<?php if ( $this->canModify ): ?>

    <p class="package-list-actions">
        <a href="/app/<?= $locale ?>/admin/package/update"
           class="update-all button-appearance"><?= $this->translate( 'admin.packages.action.updateAll', 'admin' ) ?></a>
    </p>
<?php endif ?>

    <?= $this->viewWidget( 'Grid\Core\Package\List', '', array(
        'user' => $auth->getIdentity(),
    ) ) ?>

    <form class="package-list-form" method="post" action="?">
        <p class="package-list-search">
<?php if ( $this->canModify ): ?>

            <select name="filter[installed]">
                <option value=""<?php if ( null === $filter['installed'] ):
                    ?> selected="selected"<?php endif ?>>
                    <?= $this->translate( 'admin.packages.installed.all', 'admin' ) ?>

                </option>
                <option value="1"<?php if ( $filter['installed'] ):
                    ?> selected="selected"<?php endif ?>>
                    <?= $this->translate( 'admin.packages.installed.only', 'admin' ) ?>

                </option>
                <option value="0"<?php if ( null !== $filter['installed'] && ! $filter['installed'] ):
                    ?> selected="selected"<?php endif ?>>
                    <?= $this->translate( 'admin.packages.installed.not', 'admin' ) ?>

                </option>
            </select>
<?php else: ?>

            <input type="hidden" name="filter[installed]" value="1" />
<?php endif ?>

            <label title="<?= $this->escapeHtmlAttr( $this->translate( 'admin.packages.contains', 'admin' ) ) ?>">
                <input type="search" name="filter[contains]" value="<?= $this->escapeHtmlAttr( $filter['contains'] ) ?>" />
            </label>
            <button type="submit">
                <?= $this->translate( 'admin.packages.search', 'admin' ) ?>

            </button>
        </p>
        <?= $paginationControl = $this->paginationControl(
            $paginator,
            'Sliding',
            'paginator/default'
        ) ?>

    </form>
    <div class="package-list">
<?php if ( ! $paginator->getTotalItemCount() ): ?>

        <div class="warn package-list-empty">
            <?= $this->translate( 'default.rowSet.noData' ) ?>
        </div>
<?php else: ?>

<?php foreach ( $paginator as $name => $package ): ?>
<?php if ( $package && $package->isValid() ): ?>

        <div id="package-<?= $package->idSafeName ?>" class="package-entry<?php
                if ( $package->isInstalled() ): ?> installed<?php
                if ( empty( $package->module ) || $this->isModuleLoaded( $package->module ) ): ?> enabled<?php endif ?><?php endif ?>">
            <img class="icon" src="/images/common/blank.gif"
<?php $icon = $package->getDisplayedIcon( 64 ); if ( ! empty( $icon ) ): ?>

                 style="background-image: url(<?= $this->escapeHtmlAttr( $icon ) ?>);"
<?php endif ?>

                 title="<?= $this->escapeHtmlAttr( $name ) ?>"
                 alt="<?= $this->escapeHtmlAttr( $name ) ?>" />
            <p class="name">
                <?= $this->escapeHtml( $package->getDisplayedName( $locale ) ) ?>

            </p>
            <div class="short-infos">
<?php if ( isset( $package->installedTime ) ): ?>

                <span class="time-label"><?= $this->translate( 'admin.packages.installedTime', 'admin' ) ?>:</span>
                <span class="time-value" title="<?= $this->escapeHtmlAttr( $this->dateTime( $package->installedTime ) ) ?>"><?= $this->relativeTime( $package->installedTime ) ?></span>
<?php elseif ( isset( $package->availableTime ) ): ?>

                <span class="time-label"><?= $this->translate( 'admin.packages.availableTime', 'admin' ) ?>:</span>
                <span class="time-value" title="<?= $this->escapeHtmlAttr( $this->dateTime( $package->availableTime ) ) ?>"><?= $this->relativeTime( $package->availableTime ) ?></span>
<?php endif ?>
            </div>
            <div class="contents">
                <div class="description">
                    <?= $this->markdown( $package->getDisplayedDescription( $locale ) ) ?>

                </div>
<?php if ( isset( $package->favourites ) || isset( $package->downloads ) ): ?>

                <div class="numbers">
<?php if ( isset( $package->favourites ) ): ?>

                    <span class="number favourites" title="<?= $this->translate( 'admin.packages.favourites', 'admin' )
                        ?>"><?= (int) $package->favourites ?></span>
<?php endif ?>
<?php if ( isset( $package->downloads ) ): ?>

                    <span class="number downloads" title="<?= $this->translate( 'admin.packages.downloads', 'admin' )
                        ?>"><?= (int) $package->downloads ?></span>
<?php endif ?>

                </div>
<?php endif ?>

                <dl class="package-data">
<?php if ( ! empty( $package->homepage ) ): ?>

                    <dt class="homepage"><?= $this->translate( 'admin.packages.homepage', 'admin' ) ?></dt>
                    <dd class="homepage"><a href="<?= $this->escapeHtmlAttr( $package->homepage ) ?>"
                                            target="_blank"><?= $this->escapeHtml( $package->homepage ) ?></a></dd>
<?php endif ?>
<?php if ( ! empty( $package->license ) ): ?>

                    <dt class="license"><?= $this->translate( 'admin.packages.license', 'admin' ) ?></dt>
                    <dd class="license">
<?php foreach ( $package->licenseUris as $license => $uri ): ?>
<?php if ( $uri ): ?>

                        <a href="<?= $this->escapeHtmlAttr( $uri ) ?>"
                           target="_blank"><?= $this->escapeHtml( $license ) ?></a>
<?php else: ?>

                        <span><?= $this->escapeHtml( $license ) ?></span>
<?php endif ?>
<?php endforeach ?>

                    </dd>
<?php endif ?>
<?php if ( ! empty( $package->keywords ) ): ?>

                    <dt class="keywords"><?= $this->translate( 'admin.packages.keywords', 'admin' ) ?></dt>
                    <dd class="keywords"><?= $this->escapeHtml( implode( ', ', $package->keywords ) ) ?></dd>
<?php endif ?>
<?php $authors = $package->getDisplayedAuthors( $locale ); if ( ! empty( $authors ) ): ?>

                    <dt class="authors"><?= $this->translate( 'admin.packages.authors', 'admin' ) ?></dt>
                    <dd class="authors">
<?php foreach ( $authors as $author ): ?>

                        <a href="<?= empty( $author['url'] ) ? '#' : $author['url'] ?>" target="_blank"
                           class="author"><?= $this->escapeHtml( $author['name'] ) ?></a>
<?php endforeach ?>

                    </dd>
<?php endif ?>
<?php if ( ! empty( $package->installedVersion ) ): ?>

                    <dt class="installed version"><?= $this->translate( 'admin.packages.installedVersion', 'admin' ) ?></dt>
                    <dd class="installed version"<?php if ( ! empty( $package->installedReference ) ): ?>

                        title="#<?= $this->escapeHtmlAttr( $package->installedReference ) ?>"<?php endif ?>>
                        <?= $this->escapeHtml( $package->installedVersion ) ?>

                    </dd>
<?php endif ?>
<?php if ( ! empty( $package->installedTime ) ): ?>

                    <dt class="installed time"><?= $this->translate( 'admin.packages.installedTime', 'admin' ) ?></dt>
                    <dd class="installed time" title="<?= $this->escapeHtmlAttr( $this->dateTime( $package->installedTime ) ) ?>">
                        <?= $this->relativeTime( $package->installedTime ) ?>

                    </dd>
<?php endif ?>
<?php if ( ! empty( $package->availableVersion ) && ( $package->canModify() || empty( $package->installedVersion ) ) ): ?>

                    <dt class="available version"><?= $this->translate( 'admin.packages.availableVersion', 'admin' ) ?></dt>
                    <dd class="available version"<?php if ( ! empty( $package->availableReference ) ): ?>

                        title="#<?= $this->escapeHtmlAttr( $package->availableReference ) ?>"<?php endif ?>>
                        <?= $this->escapeHtml( $package->availableVersion ) ?>

                    </dd>
<?php endif ?>
<?php if ( ! empty( $package->availableTime ) ): ?>

                    <dt class="available time"><?= $this->translate( 'admin.packages.availableTime', 'admin' ) ?></dt>
                    <dd class="available time" title="<?= $this->escapeHtmlAttr( $this->dateTime( $package->availableTime ) ) ?>">
                        <?= $this->relativeTime( $package->availableTime ) ?>

                    </dd>
<?php endif ?>
<?php if ( $package->canModify() ): ?>

                    <dt class="library-name"><?= $this->translate( 'admin.packages.libraryName', 'admin' ) ?></dt>
                    <dd class="library-name"><?= $this->escapeHtml( $package->name ) ?></dd>
                    <dt class="library-description"><?= $this->translate( 'admin.packages.libraryDescription', 'admin' ) ?></dt>
                    <dd class="library-description"><?= $this->escapeHtml( $package->description ) ?></dd>
<?php endif ?>

                </dl>
            </div>
<?php if ( ! empty( $package->installedVersion ) && ! empty( $package->module ) ): ?>

            <form class="modules" method="post" action="?">
                <input name="page" type="hidden" value="<?= $this->escapeHtmlAttr( $this->page ) ?>" />
                <input name="filter[contains]" type="hidden" value="<?= $this->escapeHtmlAttr( $filter['contains'] ) ?>" />
<?php if ( $this->canModify ): ?>

                <input name="filter[installed]" type="hidden" value="<?= $filter['installed'] === null ? '' : ( $filter['installed'] ? '1' : '0' ) ?>" />
<?php endif ?>

                <input type="hidden" name="modules[<?= $this->escapeHtmlAttr( $package->module ) ?>]" value="" />
<?php $this->placeholder( 'listModule' )->set( '' );
      $this->placeholder( 'listModule' )->captureStart(); ?>

                <label class="module">
                    <input type="checkbox" data-js-type="js.form.submit js.form.element.onOff"
                           name="modules[<?= $this->escapeHtmlAttr( $package->module ) ?>]"
                           value="1"<?php if ( $this->isModuleLoaded( $package->module ) ):
                        ?> checked="checked"<?php endif ?> />
                </label>
<?php $this->placeholder( 'listModule' )->captureEnd(); ?>

                <?= $this->viewWidget(
                    'Grid\Core\Package\List\Module',
                    $this->placeholder( 'listModule' ),
                    array(
                        'package'   => $package,
                        'module'    => $package->module,
                    )
                ) ?>

            </form>
<?php endif ?>
<?php if ( $package->canInstall() || $package->canRemove() ): ?>

            <div class="actions">
<?php if ( $package->canInstall() ): ?>

                <a href="/app/<?= $locale ?>/admin/package/install/<?= $package->urlSafeName ?>"
                   class="action install button-appearance"><?= $this->translate( 'admin.packages.action.install', 'admin' ) ?></a>
<?php elseif ( $package->canRemove() ): ?>

                <a href="/app/<?= $locale ?>/admin/package/remove/<?= $package->urlSafeName ?>"
                   onclick="return js.require('js.ui.dialog').confirm(this);"
                   class="action remove button-appearance"><?= $this->translate( 'admin.packages.action.remove', 'admin' ) ?></a>
<?php endif ?>

            </div>
<?php endif ?>

        </div>
<?php else: ?>

        <div class="warn package-entry-invalid">
            <!-- invalid package: "<?= $name ?>" -->
        </div>
<?php endif ?>
<?php endforeach ?>
<?php endif ?>

    </div>

    <form class="package-list-form" method="post" action="?">
        <input name="filter[contains]" type="hidden" value="<?= $this->escapeHtmlAttr( $filter['contains'] ) ?>" />
<?php if ( $this->canModify ): ?>

        <input name="filter[installed]" type="hidden" value="<?= $filter['installed'] === null ? '' : ( $filter['installed'] ? '1' : '0' ) ?>" />
<?php endif ?>

        <?= $paginationControl ?>

    </form>
</div>
