<?php
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$this->headTitle( $title = $this->translate(
    'admin.navTop.packages',
    'admin'
) );

$paginator = $this->paginator;

$paginator->setPageRange( 7 )
          ->setItemCountPerPage( 5 )
          ->setCurrentPageNumber( $this->page );

$this->headLink()
     ->appendStylesheet( '/styles/packages.css' );

$filter = (array) $this->filter;

if ( empty( $filter['category'] ) )
{
    $filter['category'] = '';
}

if ( empty( $filter['contains'] ) )
{
    $filter['contains'] = '';
}

if ( ! isset( $filter['installed'] ) || '' === $filter['installed'] )
{
    $filter['installed'] = null;
}

?>
<h1><?= $title ?></h1>
<div class="page">
    <form class="package-list-form" method="post" action="?">
        <p class="package-list-actions">
<?php if ( $this->canModify ): ?>

            <a href="/app/<?= $this->locale() ?>/admin/package/update"
               class="update-all button-appearance"><?= $this->translate( 'admin.packages.action.updateAll', 'admin' ) ?></a>
        </p>
<?php endif ?>

        <p class="package-list-categories">
            <input name="filter[category]" type="hidden" value="<?= $filter['category'] ?>" />
            <button name="filter[category]" type="submit"
                    value=""<?php if ( '' == $filter['category'] ):
                 ?> class="active"<?php endif ?>>
                <?= $this->translate( 'admin.packages.category.all', 'admin' ) ?>
            </button>
<?php foreach ( $this->categories as $category ): ?>

            <button name="filter[category]" type="submit"
                    value="<?= $category ?>"<?php if ( $category == $filter['category'] ):
                 ?> class="active"<?php endif ?>>
                <?= $this->translate( 'admin.packages.category.' . $category, 'admin' ) ?>
            </button>
<?php endforeach ?>

        </p>
        <p class="package-list-search">
<?php if ( $this->canModify ): ?>

            <select name="filter[installed]">
                <option value=""<?php if ( null === $filter['installed'] ):
                    ?> selected="selected"<?php endif ?>>
                    <?= $this->translate( 'admin.packages.installed.all', 'admin' ) ?>

                </option>
                <option value="1"<?php if ( $filter['installed'] ):
                    ?> selected="selected"<?php endif ?>>
                    <?= $this->translate( 'admin.packages.installed.only', 'admin' ) ?>

                </option>
                <option value="0"<?php if ( null !== $filter['installed'] && ! $filter['installed'] ):
                    ?> selected="selected"<?php endif ?>>
                    <?= $this->translate( 'admin.packages.installed.not', 'admin' ) ?>

                </option>
            </select>
<?php else: ?>

            <input type="hidden" name="filter[installed]" value="1" />
<?php endif ?>

            <label title="<?= $this->escapeHtmlAttr( $this->translate( 'admin.packages.contains', 'admin' ) ) ?>">
                <input type="search" name="filter[contains]" value="<?= $this->escapeHtmlAttr( $filter['contains'] ) ?>" />
            </label>
            <button type="submit">
                <?= $this->translate( 'admin.packages.search', 'admin' ) ?>
            </button>
        </p>
        <?= $paginationControl = $this->paginationControl(
            $paginator,
            'Sliding',
            'paginator/default'
        ) ?>

        <div class="package-list">
<?php if ( ! $paginator->getTotalItemCount() ): ?>

            <div class="warn package-list-empty">
                <?= $this->translate( 'default.rowSet.noData' ) ?>
            </div>
<?php else: ?>

<?php foreach ( $paginator as $name => $package ): ?>
<?php if ( $package && $package->isValid() ): ?>

            <div class="package-entry">
                <a href="/app/<?= $this->locale() ?>/admin/package/view/<?= $package->urlSafeName ?>"
                   class="icon-link"><img
                   class="icon" src="/images/common/blank.gif"
<?php if ( $package->displayIcon ): ?>

                   style="background-image: url(<?= $this->escapeHtmlAttr( $package->displayIcon ) ?>);"
<?php endif ?>

                   alt="<?= $this->escapeHtmlAttr( $name ) ?>"/></a>
                <div class="name">
<?php if ( $package->canInstall() ): ?>

                    <a href="/app/<?= $this->locale() ?>/admin/package/install/<?= $package->urlSafeName ?>"
                       class="action install button-appearance"><?= $this->translate( 'admin.packages.action.install', 'admin' ) ?></a>
<?php elseif ( $package->canRemove() ): ?>

                    <a href="/app/<?= $this->locale() ?>/admin/package/remove/<?= $package->urlSafeName ?>"
                       onclick="return js.require('js.ui.dialog').confirm(this);"
                       class="action remove button-appearance"><?= $this->translate( 'admin.packages.action.remove', 'admin' ) ?></a>
<?php endif ?>

                    <a href="/app/<?= $this->locale() ?>/admin/package/view/<?= $package->urlSafeName ?>"
                       class="name-link"><?= $this->escapeHtml( $package->displayedName ) ?></a>
                </div>
                <div class="short-time">
<?php if ( isset( $package->installedTime ) ): ?>

                    <?= $this->translate( 'admin.packages.installedTime', 'admin' ) ?>:
                    <?= $this->dateTime( $package->installedTime ) ?>
<?php elseif ( isset( $package->availableTime ) ): ?>

                    <?= $this->translate( 'admin.packages.availableTime', 'admin' ) ?>:
                    <?= $this->dateTime( $package->availableTime ) ?>
<?php endif ?>

                </div>
                <div class="description">
                    <?= nl2br( $this->escapeHtml( $package->displayedDescription ) ) ?>

                    <a href="/app/<?= $this->locale() ?>/admin/package/view/<?= $package->urlSafeName ?>"
                       class="action view button-appearance"><?= $this->translate( 'admin.packages.action.view', 'admin' ) ?></a>
                </div>
            </div>
<?php else: ?>

            <div class="warn package-entry-invalid">
                <!-- invalid package: "<?= $name ?>" -->
            </div>
<?php endif ?>
<?php endforeach ?>
<?php endif ?>

        </div>

        <?= $paginationControl ?>

    </form>
</div>
