<?php
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$this->headTitle( $title = $this->translate(
    'admin.navTop.packages',
    'admin'
) );

$paginator = $this->paginator;

$paginator->setPageRange( 7 )
          ->setItemCountPerPage( 5 )
          ->setCurrentPageNumber( $this->page );

?>
<h1><?= $title ?></h1>
<div class="page">
    <form class="package-list">
        <?= $paginationControl = $this->paginationControl(
            $paginator,
            'Sliding',
            'paginator/default'
        ) ?>

        <div class="package-list">
<?php if ( ! $paginator->getTotalItemCount() ): ?>

            <div class="warn package-list-empty">
                <?= $this->translate( 'default.rowSet.noData' ) ?>
            </div>
<?php else: ?>

<?php foreach ( $paginator as $name => $package ): ?>
<?php if ( $package && $package->isValid() ):
                $link = '/app/'
                    . $this->locale()
                    . '/admin/package/'
                    . implode(
                        '',
                        array_map(
                            'rawurlencode',
                            explode( '/', $name )
                        )
                    ) ?>

            <a class="package-entry"
               href="<?= $this->escapeHtmlAttr( $link ) ?>">
                <img class="icon" src="/images/common/blank.gif"
<?php if ( $package->displayIcon ): ?>

                     style="background-image: url(<?= $this->escapeHtmlAttr( $package->displayIcon ) ?>);"
<?php endif ?>

                     alt="<?= $this->escapeHtmlAttr( $name ) ?>"/>
                <strong class="name">
                    <?= $this->escapeHtml( $package->displayedName ) ?>
                </strong>
                <span class="description">
                    <?= $this->escapeHtml( $package->displayedDescription ) ?>
                </span>
                <?php \Zend\Debug\Debug::dump( $package->toArray(), $name ) ?>
            </a>
<?php else: ?>

            <div class="warn package-entry-invalid">
                <!-- invalid package: "<?= $name ?>" -->
            </div>
<?php endif ?>
<?php endforeach ?>
<?php endif ?>

        </div>

        <?= $paginationControl ?>

    </form>
</div>
