<?php
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$this->headTitle( $title = sprintf(
    $this->translate( 'admin.navTop.packages.view.%s', 'admin' ),
    $this->package->displayedName
) );

$this->headLink()
     ->appendStylesheet( '/styles/packages.css' );

?>
<h1><?= $title ?></h1>
<div class="page">
    <p class="info">
        <?= $this->translate( 'admin.packages.update.inProgress', 'admin' ) ?>

    </p>
    <div data-js-type="js.admin.updatePackages">
        <div class="messages"></div>
        <details>
            <summary><?= $this->translate( 'admin.packages.update.details', 'admin' ) ?></summary>
            <pre class="output"></pre>
        </details>
    </div>
</div>
