<?php
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$this->headTitle(
    $title = $this->translate( 'admin.packages.action.updateAll', 'admin' )
);

$this->headLink()
     ->appendStylesheet( '/styles/packages.css' );

?>
<h1><?= $title ?></h1>
<div class="page">
    <h3>
        <?= $this->translate( 'admin.packages.update.inProgress', 'admin' ) ?>

    </h3>
    <div data-js-type="js.admin.updatePackages">
        <div class="messages">&nbsp;</div>
        <details>
            <summary><?= $this->translate( 'admin.packages.update.details', 'admin' ) ?></summary>
            <pre class="output">&nbsp;</pre>
        </details>
    </div>
</div>
