<?php
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$locale         = (string) $this->locale();
$packageName    = $this->package->getDisplayedName( $locale );

$this->headTitle( $title = sprintf(
    $this->translate( 'admin.navTop.packages.view.%s', 'admin' ),
    $packageName
) );

$this->headLink()
     ->appendStylesheet( '/styles/packages.css' );

?>
<h1><?= $title ?></h1>
<div class="page">
    <form class="package-details" method="post" action="?">
        <h3 class="name">
            <?= $this->escapeHtml( $packageName ) ?>

        </h3>
<?php if ( $this->package && $this->package->isValid() ): ?>
<?php if ( $this->package->canInstall() ): ?>

                    <a href="/app/<?= $locale ?>/admin/package/install/<?= $this->package->urlSafeName ?>"
                       class="action install button-appearance"><?= $this->translate( 'admin.packages.action.install', 'admin' ) ?></a>
<?php elseif ( $this->package->canRemove() ): ?>

                    <a href="/app/<?= $locale ?>/admin/package/remove/<?= $this->package->urlSafeName ?>"
                       onclick="return js.require('js.ui.dialog').confirm(this);"
                       class="action remove button-appearance"><?= $this->translate( 'admin.packages.action.remove', 'admin' ) ?></a>
<?php endif ?>

        <img class="icon" src="/images/common/blank.gif"
<?php $icon = $this->package->getDisplayedIcon(); if ( ! empty( $icon ) ): ?>

             style="background-image: url(<?= $this->escapeHtmlAttr( $icon ) ?>);"
<?php endif ?>

             alt="<?= $this->escapeHtmlAttr( $this->name ) ?>"/>
        <div class="short-infos">
<?php if ( isset( $this->package->installedTime ) ): ?>

                    <span class="time-label"><?= $this->translate( 'admin.packages.installedTime', 'admin' ) ?>:</span>
                    <span class="time-value"><?= $this->dateTime( $this->package->installedTime ) ?></span>
<?php elseif ( isset( $this->package->availableTime ) ): ?>

                    <span class="time-label"><?= $this->translate( 'admin.packages.availableTime', 'admin' ) ?>:</span>
                    <span class="time-value"><?= $this->dateTime( $this->package->availableTime ) ?></span>
<?php endif ?>
<?php if ( isset( $this->package->favourites ) ): ?>

                <span class="number favourites" title="<?= $this->translate( 'admin.packages.favourites', 'admin' )
                    ?>"><?= (int) $this->package->favourites ?></span>
<?php endif ?>
<?php if ( isset( $this->package->downloads ) ): ?>

                <span class="number downloads" title="<?= $this->translate( 'admin.packages.downloads', 'admin' )
                    ?>"><?= (int) $this->package->downloads ?></span>
<?php endif ?>

        </div>
<?php if ( ! empty( $this->package->installedVersion ) && ! empty( $this->package->modules ) ): $single = 1 == count( $this->package->modules ); ?>

        <div class="modules">
<?php foreach ( $this->package->getDisplayedModules( $locale ) as $moduleName => $moduleLabel ): ?>

            <label class="module" onclick="this.blur();">
                <input type="hidden" name="modules[<?= $this->escapeHtmlAttr( $moduleName ) ?>]" value="" />
                <input type="checkbox" name="modules[<?= $this->escapeHtmlAttr( $moduleName ) ?>]" value="1"<?php if ( $single ):
                    ?> onchange="this.form.submit();"<?php endif ?><?php if ( $this->isModuleLoaded( $moduleName ) ):
                    ?> checked="checked"<?php endif ?> />
                <?= $this->escapeHtml( $moduleLabel ) ?>

            </label>
<?php endforeach ?>
<?php if ( ! $single ): ?>

            <button type="submit"><?= $this->translate( 'default.save' ) ?></button>
<?php endif ?>

        </div>
<?php endif ?>

        <div class="description">
            <?= $this->markdown( $this->package->getDisplayedDescription( $locale ) ) ?>

        </div>
        <dl class="package-data">
            <dt class="library-name"><?= $this->translate( 'admin.packages.libraryName', 'admin' ) ?></dt>
            <dd class="library-name"><?= $this->escapeHtml( $this->package->name ) ?></dd>
            <dt class="library-description"><?= $this->translate( 'admin.packages.libraryDescription', 'admin' ) ?></dt>
            <dd class="library-description"><?= $this->escapeHtml( $this->package->description ) ?></dd>
<?php if ( ! empty( $this->package->homepage ) ): ?>

            <dt class="homepage"><?= $this->translate( 'admin.packages.homepage', 'admin' ) ?></dt>
            <dd class="homepage"><a href="<?= $this->escapeHtmlAttr( $this->package->homepage ) ?>"
                                    target="_blank"><?= $this->escapeHtml( $this->package->homepage ) ?></a></dd>
<?php endif ?>
<?php if ( ! empty( $this->package->license ) ): ?>

            <dt class="license"><?= $this->translate( 'admin.packages.license', 'admin' ) ?></dt>
            <dd class="license">
<?php foreach ( $this->package->licenseUris as $license => $uri ): ?>
<?php if ( $uri ): ?>

                <a href="<?= $this->escapeHtmlAttr( $uri ) ?>"
                   target="_blank"><?= $this->escapeHtml( $license ) ?></a>
<?php else: ?>

                <span><?= $this->escapeHtml( $license ) ?></span>
<?php endif ?>
<?php endforeach ?>

            </dd>
<?php endif ?>
<?php if ( ! empty( $this->package->keywords ) ): ?>

            <dt class="keywords"><?= $this->translate( 'admin.packages.keywords', 'admin' ) ?></dt>
            <dd class="keywords"><?= $this->escapeHtml( implode( ', ', $this->package->keywords ) ) ?></dd>
<?php endif ?>
<?php if ( ! empty( $this->package->availableVersion ) ): ?>

            <dt class="available version"><?= $this->translate( 'admin.packages.availableVersion', 'admin' ) ?></dt>
            <dd class="available version">
                <?= $this->escapeHtml( $this->package->availableVersion ) ?>
<?php if ( ! empty( $this->package->availableReference ) ): ?>

                <span class="available reference">#<?= $this->escapeHtml( $this->package->availableReference ) ?></span>
<?php endif ?>

            </dd>
<?php endif ?>
<?php if ( ! empty( $this->package->availableTime ) ): ?>

            <dt class="available time"><?= $this->translate( 'admin.packages.availableTime', 'admin' ) ?></dt>
            <dd class="available time">
                <?= $this->dateTime( $this->package->availableTime ) ?>

            </dd>
<?php endif ?>
<?php if ( ! empty( $this->package->installedVersion ) ): ?>

            <dt class="installed version"><?= $this->translate( 'admin.packages.installedVersion', 'admin' ) ?></dt>
            <dd class="installed version">
                <?= $this->escapeHtml( $this->package->installedVersion ) ?>
<?php if ( ! empty( $this->package->installedReference ) ): ?>

                <span class="installed reference">#<?= $this->escapeHtml( $this->package->installedReference ) ?></span>
<?php endif ?>

            </dd>
<?php endif ?>
<?php if ( ! empty( $this->package->installedTime ) ): ?>

            <dt class="installed time"><?= $this->translate( 'admin.packages.installedTime', 'admin' ) ?></dt>
            <dd class="installed time">
                <?= $this->dateTime( $this->package->installedTime ) ?>

            </dd>
<?php endif ?>
<?php if ( isset( $this->package->favourites ) ): ?>

            <dt class="favourites"><?= $this->translate( 'admin.packages.favourites', 'admin' ) ?></dt>
            <dd class="favourites"><?= (int) $this->package->favourites ?></dd>
<?php endif ?>
<?php if ( isset( $this->package->downloads ) ): ?>

            <dt class="downloads"><?= $this->translate( 'admin.packages.downloads', 'admin' ) ?></dt>
            <dd class="downloads"><?= (int) $this->package->downloads ?></dd>
<?php endif ?>
<?php $authors = $this->package->getDisplayedAuthors( $locale ); if ( ! empty( $authors ) ): ?>

            <dt class="authors"><?= $this->translate( 'admin.packages.authors', 'admin' ) ?></dt>
            <dd class="authors">
<?php foreach ( $authors as $author ): ?>

                <a href="<?= empty( $author['url'] ) ? '#' : $author['url'] ?>" target="_blank"
                   class="author"><?= $this->escapeHtml( $author['name'] ) ?></a>
<?php endforeach ?>

            </dd>
<?php endif ?>

        </dl>
<?php else: ?>

        <div class="warn package-invalid">
            <!-- invalid package: "<?= $this->name ?>" -->
        </div>
<?php endif ?>

    </form>
</div>
