<?php

$headTitle  = $this->headTitle();
$paragraph  = $this->paragraph;
$navigation = $paragraph->navigation;
$separator  = $paragraph->separator ?: $headTitle->getSeparator();

echo $this->navigation()
          ->breadcrumbs()
          ->setMinDepth( 0 )
          ->setIndent( false )
          ->setLinkLast( true )
          ->setTranslatorEnabled( false )
          ->setSeparator(
              ' <span class="separator">' .
                  $this->escapeHtml( trim( $separator ) ) .
              '</span> '
          )
          ->renderStraight( $navigation );

?>
