<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Grid\Tag\Module'                         => __DIR__ . '/Module.php',
    'Grid\Tag\Controller\AdminController'     => __DIR__ . '/src/Grid/Tag/Controller/AdminController.php',
    'Grid\Tag\Controller\ListController'      => __DIR__ . '/src/Grid/Tag/Controller/ListController.php',
    'Grid\Tag\Controller\SearchController'    => __DIR__ . '/src/Grid/Tag/Controller/SearchController.php',
    'Grid\Tag\Form\Element\TagList'           => __DIR__ . '/src/Grid/Tag/Form/Element/TagList.php',
    'Grid\Tag\Form\View\Helper\FormTagList'   => __DIR__ . '/src/Grid/Tag/Form/View/Helper/FormTagList.php',
    'Grid\Tag\Model\Paragraph\Structure\Tags' => __DIR__ . '/src/Grid/Tag/Model/Paragraph/Structure/Tags.php',
    'Grid\Tag\Model\Tag\Mapper'               => __DIR__ . '/src/Grid/Tag/Model/Tag/Mapper.php',
    'Grid\Tag\Model\Tag\Model'                => __DIR__ . '/src/Grid/Tag/Model/Tag/Model.php',
    'Grid\Tag\Model\Tag\Rpc'                  => __DIR__ . '/src/Grid/Tag/Model/Tag/Rpc.php',
    'Grid\Tag\Model\Tag\Structure'            => __DIR__ . '/src/Grid/Tag/Model/Tag/Structure.php',
    'Grid\Tag\Model\TagsAwareInterface'       => __DIR__ . '/src/Grid/Tag/Model/TagsAwareInterface.php',
);
