<?php
$columnCnt  = 0;
$id         = $this->rowSet->getId();
$store      = $this->rowSet->getStore();
$columns    = $this->rowSet->getColumns();
$paginator  = $this->rowSet->getPaginator();

$paginator->setPageRange( $this->rowSet->getPageRange() )
          ->setItemCountPerPage( $this->rowSet->getItemCountPerPage() )
          ->setCurrentPageNumber( $this->rowSet->getPage() );
?>

<div id="rowset_<?= $id ?>" class="rowSetTableHolder">
    <?= $paginationControl = $this->paginationControl( $paginator,
                                                       'Sliding',
                                                       'paginator/default' ) ?>

    <table class="rowSet">
        <thead>
            <tr class="header">
                <?php foreach ( $store['enable'] as $column => $enabled ):
                        if ( $enabled ): $columnCnt++;
                            $type = $columns[$column];
                            $name = $this->rowSet->getColumnName( $column ); ?>

                    <th class="column name-<?= $column ?> type-<?php
                        echo lcfirst( preg_replace( '/.*\\\\/', '', get_class( $type ) ) );
                        if ( $this->rowSet->isColumnSearched( $column ) )
                            echo ' search'; ?>">
                    <?php if ( $type instanceof \Core\View\Helper\RowSet\Type\Bool ): ?>

                        <abbr title="<?= $name ?>"><?= mb_substr( $name, 0, 1 ) ?></abbr>
                    <?php else: ?>

                        <?= $name ?>

                        <?php if ( ! $type instanceof \Core\View\Helper\RowSet\Type\Translate &&
                                   ! $type instanceof \Core\View\Helper\RowSet\Type\Callback ):
                            $order = isset( $store['orders'][$column] ) ?
                                strtolower( $store['orders'][$column] ) : null; ?>
                        <input type="hidden"
                               name="orders[<?= $column ?>]"
                               value="<?= $order; ?>" />
                        <button type="submit"
                                name="orders[<?= $column ?>]"
                                value="<?php if ( $order != 'desc' ) echo 'desc'; ?>"
                                class="order desc<?php if ( $order == 'desc' ) echo ' active';
                                ?>">&#x25bc;</button>
                        <button type="submit"
                                name="orders[<?= $column ?>]"
                                value="<?php if ( $order != 'asc' ) echo 'asc'; ?>"
                                class="order asc<?php if ( $order == 'asc' ) echo ' active';
                                ?>">&#x25b2;</button>
                        <?php endif ?>

                    <?php endif ?>

                    </th>
                <?php endif; endforeach; ?>

            </tr>
        </thead>
<?php if ( ! $paginator->getTotalItemCount() ): ?>

        <tfoot>
            <tr class="row empty">
                <th colspan="<?= $columnCnt; ?>">
                    <i><?= $this->translate( 'default.rowSet.noData' ) ?></i>
                </th>
            </tr>
        </tfoot>
<?php else: ?>

        <tbody>
    <?php foreach ( $paginator as $row ): ?>

            <tr class="row">
            <?php foreach ( $store['enable'] as $column => $enabled ):
                    if ( $enabled ):
                        $type = $columns[$column];
                        $name = $this->rowSet->getColumnName( $column );
                        $value = isset( $row->$column )
                            ? $row->$column
                            : $row->getOption( $column ); ?>

                <td class="column name-<?= $column; ?> type-<?=
                        lcfirst( preg_replace( '/.*\\\\/', '', get_class( $type ) ) );?>">
                <?php if ( $this->rowSet->hasIcon( $column ) ): ?>

                    <img class="icon" alt="<?= $value ?>"
                         src="<?= $this->rowSet->getIcon( $column, $value ) ?>" />
                <?php endif ?>

                <?php if ( ! $type instanceof \Core\View\Helper\RowSet\Type\Callback &&
                         ( null === $value || '' === $value || ( is_array( $value ) && empty( $value ) ) ) ):
                          $label = null === $value
                              ? $this->rowSet->getNotSetLabel( $column )
                              : $this->rowSet->getEmptyLabel( $column ); ?>

                    <i><?= $this->translate( $label, strstr( $label, '.', true ) ) ?></i>
                <?php else: ?>

                    <?= $type->displayValue( $value, $row ) ?>

                <?php endif ?>

                </td>
            <?php endif; endforeach; ?>

            </tr>
        <?php endforeach ?>

        </tbody>
<?php endif ?>

    </table>
    <?= $paginationControl ?>
</div>
