<?php

$title   = 'HTTP 500 - Internal server error';
$message = <<<ERROR
An unexpected error has occured.
We are sorry for the inconvenience; a report of this error has sent to us successfully.
ERROR;

?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="Expires" content="-1" />
        <meta http-equiv="Pragma" content="no-cache" />
        <meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate, post-check=0, pre-check=0" />
        <title><?= htmlspecialchars( $title ) ?></title>
        <style tyle="text/css">
            /* <![CDATA[ */
            .error
            {
                width: 66%;
                padding: 2em;
                border: 1px dotted #000;
                margin: 10% auto 2em auto;
                border-color: currentColor;
            }
            /* ]]> */
        </style>
    </head>
    <body>
        <div class="error">
            <h1 class="title"><?= htmlspecialchars( $title ) ?></h1>
            <p class="message"><?= nl2br( htmlspecialchars( $message ) ) ?></p>
        </div>
<?php if ( error_reporting() & E_WARNING ): ?>
        <pre class="exception"><?= $exception ?></pre>
<?php endif ?>
    </body>
</html>
