<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Grid\Image\Module'                          => __DIR__ . '/Module.php',
    'Grid\Image\Controller\MetaController'       => __DIR__ . '/src/Grid/Image/Controller/MetaController.php',
    'Grid\Image\Controller\ThumbnailController'  => __DIR__ . '/src/Grid/Image/Controller/ThumbnailController.php',
    'Grid\Image\Model\Paragraph\Structure\Image' => __DIR__ . '/src/Grid/Image/Model/Paragraph/Structure/Image.php',
    'Grid\Image\View\Helper\Thumbnail'           => __DIR__ . '/src/Grid/Image/View/Helper/Thumbnail.php',
);
