<?php

$this->headLink()
     ->appendStylesheet( '/styles/modules/User/login.css', 'all' );

$auth       = new \Zend\Authentication\AuthenticationService();
$identity   = $auth->getIdentity();

?>

<div class="user-authentication user-logout">
    <h3><?= $this->translate( 'user.welcome', 'user' ) ?></h3>
    <p>

<?php $this->placeholder( 'userData' )->captureStart(); ?>
<?php if ( ! empty( $this->display['centralWelcomeLink'] ) &&
           $this->isAllowed( 'central', 'welcome' ) ): ?>

        <a class="linkToCentralWelcome" href="<?=
            $this->url( 'Grid\MultisiteCentral\Welcome\Index', array(
                'locale' => (string) $this->locale(),
            ) ) ?>"><?=
            $this->translate( 'central.welcome', 'central' )
           ?></a>,
<?php endif ?>

        <a class="linkToUser" href="<?=
            $this->url( 'Grid\User\Datasheet\View', array(
                'locale'        => (string) $this->locale(),
                'displayName'   => $identity->displayName,
            ) ) ?>"><?= $identity->displayName ?></a>
        <br />
        <span class="containerForEmail">
            <?= $this->escapeHtml( $identity->email ) ?>
        </span>
<?php $this->placeholder( 'userData' )->captureEnd(); ?>
<?= $this->viewWidget(
        'Grid\User\Authentication\Logout',
        (string) $this->placeholder( 'userData' ),
        array(
            'user'      => $identity,
            'display'   => $this->display,
        )
    ) ?>

    </p>

    <?= $this->form( $this->form, 'user' ) ?>

</div>
