<?php $tags = (array) $this->paragraph->renderedLocaleTags; ?>
<?php if ( empty( $tags ) ): ?>
<?php if ( $this->paragraph->isEditable() ): ?>

<p class="tags warn">
    <?= $this->translate( 'tag.paragraph.tags.empty', 'tag' ) ?>

</p>
<?php endif ?>
<?php else: ?>

<p class="tags">
    <!-- span class="label"><?= $this->translate( 'paragraph.tags.label',
                                                  'paragraph' ) ?>:</span -->
<?php $first = true;
foreach ( $tags as $tag ):
if ( $first ):
    $first = false;
else:
?><span class="tag-separator">,</span><?php endif ?>

    <a href="/app/<?= $this->locale() ?>/tag/list/all/<?=
       $this->escapeHtmlAttr( rawurlencode( $tag ) ) ?>"
       rel="tag" class="tag"><?= $this->escapeHtml( $tag ) ?></a><?php endforeach ?>

</p>
<?php endif ?>
