<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Grid\Menu\Module'                               => __DIR__ . '/Module.php',
    'Grid\Menu\Controller\AdminController'           => __DIR__ . '/src/Grid/Menu/Controller/AdminController.php',
    'Grid\Menu\Controller\NavigationController'      => __DIR__ . '/src/Grid/Menu/Controller/NavigationController.php',
    'Grid\Menu\Controller\SitemapController'         => __DIR__ . '/src/Grid/Menu/Controller/SitemapController.php',
    'Grid\Menu\Model\Menu\ConvertToNavigation'       => __DIR__ . '/src/Grid/Menu/Model/Menu/ConvertToNavigation.php',
    'Grid\Menu\Model\Menu\Mapper'                    => __DIR__ . '/src/Grid/Menu/Model/Menu/Mapper.php',
    'Grid\Menu\Model\Menu\Model'                     => __DIR__ . '/src/Grid/Menu/Model/Menu/Model.php',
    'Grid\Menu\Model\Menu\Rpc'                       => __DIR__ . '/src/Grid/Menu/Model/Menu/Rpc.php',
    'Grid\Menu\Model\Menu\Structure\Container'       => __DIR__ . '/src/Grid/Menu/Model/Menu/Structure/Container.php',
    'Grid\Menu\Model\Menu\Structure\Content'         => __DIR__ . '/src/Grid/Menu/Model/Menu/Structure/Content.php',
    'Grid\Menu\Model\Menu\Structure\DefaultFallback' => __DIR__ . '/src/Grid/Menu/Model/Menu/Structure/DefaultFallback.php',
    'Grid\Menu\Model\Menu\Structure\ProxyAbstract'   => __DIR__ . '/src/Grid/Menu/Model/Menu/Structure/ProxyAbstract.php',
    'Grid\Menu\Model\Menu\Structure\ProxyBase'       => __DIR__ . '/src/Grid/Menu/Model/Menu/Structure/ProxyBase.php',
    'Grid\Menu\Model\Menu\Structure\Uri'             => __DIR__ . '/src/Grid/Menu/Model/Menu/Structure/Uri.php',
    'Grid\Menu\Model\Menu\StructureFactory'          => __DIR__ . '/src/Grid/Menu/Model/Menu/StructureFactory.php',
    'Grid\Menu\Model\Menu\StructureInterface'        => __DIR__ . '/src/Grid/Menu/Model/Menu/StructureInterface.php',
    'Grid\Menu\Model\Paragraph\Structure\Breadcrumb' => __DIR__ . '/src/Grid/Menu/Model/Paragraph/Structure/Breadcrumb.php',
    'Grid\Menu\Model\Paragraph\Structure\Menu'       => __DIR__ . '/src/Grid/Menu/Model/Paragraph/Structure/Menu.php',
);
