<?php

/**
 * @var Zend\View\Renderer\PhpRenderer $this
 */

$this->headLink()
     ->appendStylesheet( '/styles/admin.css', 'all' );

$menu = $this->navigation( $this->navigationPages )
             ->setAcl( $this->acl )
             ->menu()
             ->setTranslatorEnabled( false );

if ( $this->hasIdentity ): ?>

    <header>
        <nav class="menu"
             data-js-type="zork.ui.menu"
             data-js-menu-corners="bottom"
             data-js-menu-orientation="horizontal">
            <?= $menu->render() ?>
        </nav>
    </header>

    <div class="adminContentContainer">
        <?php if ( ! empty( $this->adminLocaleForm ) ): ?>
            <div class="adminLocale">
                <?= $this->form( $this->adminLocaleForm, 'default' ); ?>
            </div>
        <?php
            endif;
            $ns = array_map( 'lcfirst', explode( '\\' , $this->controller ) );
            $controller = array_pop( $ns );
        ?>

        <section class="admin <?=
                 implode( '-', $ns ) . '-ns' ?> <?=
                 $controller . '-controller' ?> <?=
                 $this->action . '-action'; ?>">
<?php endif ?>

<?= $this->content ?>

<?php if ( $this->hasIdentity ): ?>
            <br class="clear" />
        </section>
    </div>
<?php endif ?>
