<?php

use Zork\Stdlib\Message;
use Zork\Mvc\Controller\Plugin\MiddleLayoutInterface;

if ( ! empty( $this->middleLayout ) &&
     $this->middleLayout instanceof MiddleLayoutInterface )
{
    $content = $this->render(
        $this->middleLayout
             ->getTemplate(),
        array_merge(
            $this->middleLayout
                 ->getVariables(),
            array(
                'content' => $this->content,
            )
        )
    );
}
else
{
    $content = $this->content;
}

$this->customCss()
     ->apply();

$this->openGraph()
     ->append( array(
         'og:locale'    => $this->openGraph()
                                ->getSafeLocale( (string) $this->locale() ),
         'og:site_name' => $this->headTitle()
                                ->slice( 0, 1 ),
     ) );

$siteInfo   = $this->siteInfo();
$indent     = '        ';

?>
<?= $this->doctype() ?>

<html lang="<?= $this->escapeHtmlAttr( $this->locale()->toIso() ) ?>">
    <head prefix="<?= $this->escapeHtmlAttr( $this->openGraph()->getPrefixAttribute() ) ?>">
        <meta charset="utf-8" />
<?= $this->headTitle()
         ->toString( $indent ) ?>

<?= $this->headMeta()
         ->appendName( 'zork:locale', (string) $this->locale() )
         ->appendName( 'zork:userlocale', (string) $this->userLocale() )
         ->appendName( 'zork:uploads', '/uploads/' . $siteInfo->getSchema() )
         ->appendName( 'zork:domain', $siteInfo->getDomain() )
         ->toString( $indent )
?>

<?= $this->headLink()
         ->toString( $indent ) ?>

<?= $this->headScript()
         ->toString( $indent ) ?>

    </head>
    <body>
        <?= $content ?>

<?= $this->inlineScript()
         ->toString( $indent )?>

<?php foreach ( $this->messenger() as $message ): ?>
        <div class="ui-helper-hidden" data-js-type="<?=
                Message::LEVEL_INFO === $message->getLevel()
                ? 'zork.ui.message' : 'zork.ui.dialog'; ?>">
<?php if ( $message->hasTranslations() ): ?>
                <?= $this->translate( $message->getMessage(), $message->getTextDomain() ) ?>
<?php else: ?>
                <?= $message->getMessage() ?>
<?php endif ?>

        </div>
<?php endforeach ?>
    </body>
</html>
