<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Grid\Mail\Module'                        => __DIR__ . '/Module.php',
    'Grid\Mail\Controller\TemplateController' => __DIR__ . '/src/Grid/Mail/Controller/TemplateController.php',
    'Grid\Mail\Model\Settings\Structure\Mail' => __DIR__ . '/src/Grid/Mail/Model/Settings/Structure/Mail.php',
    'Grid\Mail\Model\Template\Mapper'         => __DIR__ . '/src/Grid/Mail/Model/Template/Mapper.php',
    'Grid\Mail\Model\Template\Model'          => __DIR__ . '/src/Grid/Mail/Model/Template/Model.php',
    'Grid\Mail\Model\Template\Sendable'       => __DIR__ . '/src/Grid/Mail/Model/Template/Sendable.php',
    'Grid\Mail\Model\Template\Sender'         => __DIR__ . '/src/Grid/Mail/Model/Template/Sender.php',
    'Grid\Mail\Model\Template\Structure'      => __DIR__ . '/src/Grid/Mail/Model/Template/Structure.php',
);
