<?php
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$this->headTitle( strip_tags( $title = sprintf(
    $this->translate( 'mail.form.template.title.%s.%s', 'mail' ),
    $this->translate( 'mail.template.' . $this->template->name, 'mail' ),
    $this->translate( 'locale.sub.' . $this->locale, 'locale' )
) ) );
?>

<h1><?= $title ?></h1>
<div class="page">
<?php if ( $this->clone ): ?>
    <div class="info">
        <?= sprintf(
            $this->translate( 'mail.form.template.clone.%s', 'mail' ),
            $this->translate( 'locale.sub.' . $this->original, 'locale' )
        ); ?>
    </div>
<?php endif ?>
    <?= $this->form( $this->form, 'mail' ) ?>
<?php if ( null !== $this->success ): ?>
    <div data-js-type="js.ui.dialog"
         title="<?= $this->translate( 'default.' .
                  ( $this->success ? 'info' : 'error' ) ) ?>">
<?php if ( $this->success ): ?>
        <?= $this->translate( 'mail.form.template.success', 'mail' ); ?>
<?php else: ?>
        <?= $this->translate( 'mail.form.template.failed', 'mail' ); ?>
<?php endif ?>
    </div>
<?php endif ?>
</div>
